# Generated by Django 5.2 on 2025-04-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classschedule',
            name='user',
        ),
        migrations.RemoveField(
            model_name='dailytask',
            name='status',
        ),
        migrations.RemoveField(
            model_name='dailytask',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tutorialschedule',
            name='user',
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='day',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='day',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tutorialschedule',
            name='day',
            field=models.CharField(max_length=20),
        ),
    ]
